sudo: required

language: go

go:
  - 1.11.4
  - 1.12.x

services:
  - docker

env:
  - PATH=$HOME/protoc/bin:$PATH GO111MODULE=on

script:
  - make unit-test integration

after_success:
  - bash <(curl -s https://codecov.io/bash)
