ignored = ["go/doc"]

[[constraint]]
  name = "github.com/alecthomas/kingpin"
  version = "2.2.5"

[[constraint]]
  name = "github.com/alicebob/miniredis"
  version = "2.4.6"

[[constraint]]
  branch = "master"
  name = "github.com/andres-erbsen/clock"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.48"

[[constraint]]
  branch = "master"
  name = "github.com/c2h5oh/datasize"

[[constraint]]
  name = "github.com/cactus/go-statsd-client"
  version = "3.1.1"

[[constraint]]
  name = "github.com/cenkalti/backoff"
  version = "2.0.0"

[[constraint]]
  name = "github.com/docker/distribution"
  version = "2.6.2"

[[constraint]]
  name = "github.com/docker/docker-credential-helpers"
  version = "0.6.1"

[[constraint]]
  branch = "master"
  name = "github.com/docker/engine-api"

[[constraint]]
  name = "github.com/garyburd/redigo"
  version = "1.0.0"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.2.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.3.0"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "1.6.0"

[[constraint]]
  name = "github.com/pressly/chi"
  version = "2.1.0"

[[constraint]]
  name = "github.com/pressly/goose"
  version = "1.0.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/spaolacci/murmur3"
  version = "1.1.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/uber-go/tally"
  version = "3.0.0"

[[constraint]]
  name = "go.uber.org/atomic"
  version = "1.3.2"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.9.1"

[[override]]
  name = "github.com/miekg/dns"
  version = "01d59357d468872339068bcd5d55a00e2463051f"

[prune]
  go-tests = true
  unused-packages = true
